version: "3.9"
services:
  asl:
    build: .
    ports:
      - "8502:8502"      # HOST:CONTENEDOR
    devices:
        - "/dev/video0:/dev/video0"
    group_add:
      - "44"
    environment:
      OPENCV_VIDEOIO_PRIORITY_BACKEND: "V4L2"
    restart: unless-stopped
